EDITOR
marsiitr/Wall-Art-Bot pull request #1
Opened 2021-08-06 14:48 UTC by aries2001

2021-08-07 07:02 UTC, theobscuredev requested changes
@aries2001 Changes are required!

1. The 'src' folder is missing!! Include the Arduino & Image Processing code in the src folder. Follow proper file structure as mentioned in the documentation guidelines.
2. It is highly suggested you follow a uniform naming convention for all files in each of the directories.. Either resort to camelCase (For eg: AlanWalkerLogo.mp4) or underscores (Alan_Walker_Logo.mp4) or hyphens (Alan-Walker-Logo.mp4), but make sure it is uniform.
2. Make the suggested changes in the README file. Particularly,
       a. Look out for line breaks and spaces. Focus on the aesthetics.
       b. Center align all the images and justify the text using the suggested tags. Tabulate the 
           cost structure and resize few images.
       c. Refer the guidelines for the section order. Cost Structure should be included after 
           Mechanical and Electronics Aspects.
       d. Hyperlinking
3. Prepare a poster (in jpeg format) containing the proper content & logos. Refer the guidelines for the same.
4. Rename the folders as per the guidelines. For eg: Poster and Report, Images and Videos etc. , they should be named as mentioned in the guidelines.
5. Create separate 'Images' & 'Videos' folder inside the 'Images and Videos' directory and add the corresponding files in their respective folders. Remove the workflow image from 'Poster and Report' and include it in the 'Images' folder.
6. Review the entire codebase and focus on line breaks, indentation & spaces. Work on the aesthetics. Remove unnecessary lines and add comments wherever necessary.
7. Rename all the files. Avoid naming them as 'final_2.py' etc. Naming should be self-explanatory and indication of the content included in the same.

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +The main aim of this project is to draw a desired sketch on a wall.
Add a new line between this text and the following Image.

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +![](Image%20and%20Videos/Mechanical%20Design%20Images/Multiple%20view.png)
Center align all the images using the `<p>` paragraph tag and `align` attribute. For eg:
`<p align="center">`
  `<img src="https://github.com........." alt="LED Matrix">`
  `<i>LED Matrix</i>`
`</p>`

Also resize the images by assigning the dimensions.

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +* Total- Rs.3040
Tabulate the Cost Structure table. Refer this for the markdown syntax: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

Also cost structure should be included after the Mechanical & Electronic Aspects. Refer the documentation for the same.

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +We always want to draw pictures from what we see scrolling on the web. But it's always difficult to convince the professional painter to draw the exact same picture on our walls. This project helps u
Justify the entire text using the `<p>` paragraph tag and `justify` attribute. Make sure you justify all the paragraphs separately. For eg:
`<p align="justify">`
  `<h2>Abstract</h2>`
  `<p>A Rube Goldberg Machine is .........................</p>`
`</p>`

Refer this README for the same: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +   #### 1.Pulley Movement
Insert a space for aesthetic purposes only. For eg:
1. Pulley Movement

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +   #### 2.Pen Module
Insert a space for aesthetic purposes only.

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> + In this project, OpenCV is used for image processing and the coordinates are stored in the form of a 30-30 array. Which are sent to arduino through serial transfer library. Then every coordinate is
Elaborate the Electronics Aspect. Maybe include an image depicting the connections between Arduino and the necessary sensors using TinkerCAD. For eg: https://github.com/theobscuredev/Rube-Goldberg-Machine/blob/master/Images%20and%20Videos/Images/Line_Follower_Without_LSA.jpg

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +The wall art bot is planned to draw or sketch a picture which the user has in his laptop or phone.
Elaborate the Applications.

2021-08-07 07:02 UTC, theobscuredev commented on README.md
> +2. [Parul Chaudhary]
Hyperlink the GithubID of your mentors.

2021-08-07 07:02 UTC, theobscuredev commented on Image and Videos/Mechanical Design Images/1
> +
Content Missing?

2021-08-07 07:02 UTC, theobscuredev commented on Image Processing/file
> +
Missing Content? Either Delete this file or update.

2021-08-07 07:02 UTC, theobscuredev commented on Simulation/file
> +
Missing content? Either delete or update this file

2021-08-07 07:02 UTC, theobscuredev commented on Arduino/final_wall_art_2.ino
> +// Initialize with pin sequence IN1-IN3-IN2-IN4 for using the AccelStepper with 28BYJ-48
Include line breaks and work on code aesthetics. Remove unnecessary and blank lines etc.

2021-08-07 11:16 UTC, theobscuredev commented
@shikhar2624 @trishit-byte Lemme know once you've made the final changes. Make sure to tag me (@) in this thread.

2021-08-07 14:31 UTC, theobscuredev requested changes
@shikhar2624 Insert 's' while naming the 'Images and Videos' folder and update readme. Just these final changes and we're good to go

2021-08-07 14:31 UTC, theobscuredev commented on README.md
>  Open Projects 2021
Apply header using '## Open Projects 2021'

2021-08-07 14:31 UTC, theobscuredev commented on README.md
> +* https://www.hackster.io/fredrikstridsman/stringent-the-15-wall-plotter-d965ca#overview
Hyperlink the References properly. No need to link the URLs again. Refer this README: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 18:25 UTC, theobscuredev commented
@shikhar2624 & team,
Make the following final changes:

1. Rectify the naming of the folder: ~~Image and Videos~~ -> Images and Videos
2. Try to elaborate the control part in a few statements after the diagram.

Make these changes and then we're good to go!

2021-08-07 19:42 UTC, theobscuredev commented
Nice work!
@SanjeevKrishnan I suggest for merge

2021-08-08 04:15 UTC, SanjeevKrishnan requested changes
README.md looks nice!
Few changes are expected
1. Folder "Wall-Art-Bot/Image and Videos/Electronics Mechanism" is not making any sense. Shift the contents of "Electronics Mechanism" into "Wall-Art-Bot/Image and Videos/Images"
2. Folder "Wall-Art-Bot/Image and Videos/Mechanical Design Images" has to be present under "Wall-Art-Bot/Mechanical Design" folder, not under "Wall-Art-Bot/Images and Videos"
3. Rename "wall art bot.pdf" as "Report.pdf"
4. Create a subfolder "Matlab" under the folder "Wall-Art-Bot/Simulation" and shift the contents of "Wall-Art-Bot/Simulation" into "Wall-Art-Bot/Simulation/Matlab". Add "Wall-Art-Bot/Simulation/README.md" and elaborate on simulation.
5. Create a subsection "Simulation" in "Wall-Art-Bot/README.md" and give a summary and reference of "Wall-Art-Bot/Simulation/README.md" in that.
For points 4 and 5, refer to [RoverSim Documentation](https://github.com/marsiitr/RoverSim).
6. Cost Structure must include cost for manufacturing the bot. In your case, 3D printing cost has to be included.

2021-08-09 07:21 UTC, SanjeevKrishnan approved these changes
Great efforts team! Impressive work
PR looks good. Merging the PR

2021-08-09 07:21 UTC, merged